import type { MetadataRoute } from "next";

import { getSiteUrl } from "@/lib/seo/site-url";

/**
 * Native Next.js 15 robots file (app/robots.ts -> MetadataRoute.Robots).
 * Admin panel and API routes stay out of the crawl; everything else is
 * public. Points crawlers at the sitemap generated by app/sitemap.ts.
 */
export default function robots(): MetadataRoute.Robots {
  const baseUrl = getSiteUrl();

  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: ["/admin", "/api"],
    },
    sitemap: `${baseUrl}/sitemap.xml`,
  };
}
